<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-01-22 at 09:30:28.
 */
class HTMLTagTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var HTMLTag
     */
    protected $ht;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->ht = new HTMLTag;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers HTMLTag::jsScriptTag
     */
    public function testJsScriptTag()
    {
        $this->assertEquals("<script src=\"a.js\"></script>\n",$this->ht->jsScriptTag("a.js"));
    }

    /**
     * @covers HTMLTag::cssLinkTag
     */
    public function testCssLinkTag()
    {
        $this->assertEquals("<link rel=\"stylesheet\" href=\"a.css\"/>\n",$this->ht->cssLinkTag("a.css"));
    }

    /**
     * @covers HTMLTag::cssStyleTag
     */
    public function testCssStyleTag()
    {
        $arr = array("a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css","a.css");

        $csstag = $this->ht->cssStyleTag($arr);
        preg_match_all("/a.css/",$csstag,$rarr);
        preg_match_all("/<style>/",$csstag,$sarr);

        $this->assertEquals(count($arr),count($rarr[0]));//标签中a.css数量应该和数组里的一样多
        $this->assertEquals(2,count($sarr[0]));//超过30个，应该有两个<style>

    }

    /**
     * @covers HTMLTag::CommentTag
     */
    public function testCommentTag()
    {
         $this->assertEquals('<!-- comments -->',$this->ht->commentTag('comments'));

    }

    /**
     * @covers HTMLTag::ScriptTag
     */
    public function testScriptTag()
    {
         $this->assertEquals('<script>var a = 1;</script>',$this->ht->scriptTag('var a = 1;'));

    }

}
