<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-12 at 08:49:18.
 */
class PTest extends PHPUnit_Framework_TestCase
{
    protected function tearDown(){
        P::dispose();
    }
    /**
     * 测试参数值设置与获取
     * @covers P::recordGET
     * @covers P::set
     * @covers P::get
     */
    public function testInitGETParam()
    {

        P::set("c1","c1value");
        P::set("c3","c3value");
        P::initGETParam(array(
            "c1" => "c1realvalue",
            "c2" => "c2realvalue",
            "c4" => "c4realvalue",
            "c5" => "auto",
            "c7" => "c7realvalue"
        ));

        $this->assertEquals('c3value',P::get('c3'));
        $this->assertEquals('c1realvalue',P::get('c1'));
        /*
        P::set("c3","newc3value");
        P::set("c1","newc1value");


        $this->assertEquals('newc3value',P::get('c3'));
        $this->assertEquals('c1realvalue',P::get('c1'));*/

    }


}
